"""
Utilities for accessing LOD Viewer outputs.

These outputs are stored as mesh attributes (generated by .MSFS_2024_LOD_Viewer modifier).
"""
from typing import Any

import bpy

from enum import Enum
import mathutils

from dataclasses import dataclass


class LODViewerAttributeNames(Enum):
    CURRENT_LOD_INDEX = "current_lod_index"
    LOD_SCREEN_RATIO = "lod_screen_ratio"
    DISTANCE_TO_CAM = "distance_to_cam"
    LOD_COUNT = "lod_count"
    BPSHERE_LOCATION = "bsphere_location"

@dataclass
class LODViewerOutputs():
    current_lod_index : int = -1
    lod_screen_ratio : float = 0.5
    distance_to_cam : float = 0.01
    lod_count: int = 1
    bpshere_location: mathutils.Vector = mathutils.Vector((0,0,0))

def get_mesh_attribute_first_value(
    attrib_name: str, 
    mesh: bpy.types.Mesh
) -> None | Any:

    if attrib_name not in mesh.attributes:
        return None
    
    mesh_attrib = mesh.attributes.get(attrib_name)
    if not mesh_attrib:
        return None
    
    data = mesh_attrib.data

    value = None
    try:
        first_elem = data[0]
        if hasattr(first_elem, "value"):
            value = first_elem.value
        elif hasattr(first_elem, "vector"):
            value = first_elem.vector.copy()
    except:
        return None
    
    return value

def get_lod_viewer_outputs(
    depsgraph: bpy.types.Depsgraph, 
    obj: bpy.types.Object
) -> LODViewerOutputs | None:

    eval_obj = obj.evaluated_get(depsgraph)
    mesh = eval_obj.data
    current_lod_index = get_mesh_attribute_first_value(
        LODViewerAttributeNames.CURRENT_LOD_INDEX.value, mesh
    )

    if current_lod_index is None :
        return None

    lod_screen_ratio = get_mesh_attribute_first_value(
        LODViewerAttributeNames.LOD_SCREEN_RATIO.value, mesh
    )
    if lod_screen_ratio is None :
        return None

    distance_to_cam = get_mesh_attribute_first_value(
        LODViewerAttributeNames.DISTANCE_TO_CAM.value, mesh
    )

    if distance_to_cam is None :
        return None

    lod_count = get_mesh_attribute_first_value(
        LODViewerAttributeNames.LOD_COUNT.value, mesh
    )

    if lod_count is None :
        return None

    bpshere_location = get_mesh_attribute_first_value(
        LODViewerAttributeNames.BPSHERE_LOCATION.value, mesh
    )

    if bpshere_location is None :
        return None

    return LODViewerOutputs(
        int(current_lod_index),
        lod_screen_ratio,
        distance_to_cam,
        int(lod_count),
        bpshere_location,
    )